version: "3.4"
services:
  matsim:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: matsim-standard
    hostname: matsim
    restart: never
    deploy:
      mode: 'global'
    ports: []
  matsim-project:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - MATSIM_PROJECT=project
        - MATSIM_CONTRIBS=accidents accessibility
    container_name: matsim-project
    hostname: matsim
    restart: never
    deploy:
      mode: 'global'
    ports: []
  matsim-debug:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: matsim-debug
    hostname: matsim
    entrypoint: /bin/bash
    restart: never
    deploy:
      mode: 'global'
    ports: []
    volumes:
      - .:/opt/matsim
