version: "3.4"
services:
  matsim:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - INIRAM=-Xms8g
      - MAXRAM=-Xmx8g
    container_name: matsim-standard
    hostname: matsim
    restart: never
    deploy:
      mode: 'global'
    ports: []
  matsim-debug:
    extends:
      file: docker-compose.yml
      service: matsim
    entrypoint: /bin/bash
    volumes:
      - .:/opt/matsim
  matsim-ftm-tum-sbb:
    extends:
      file: docker-compose.yml
      service: matsim
    build:
      args:
        - MATSIM_PROJECT=ftm-tum-sbb
        - MATSIM_CONTRIBS=sbb-extensions
    container_name: matsim-ftm-tum-sbb
    volumes:
      - ./data/input/scenario-sim-6/:/opt/matsim/data/input
      - ./data/output:/opt/matsim/data/output
